export const countryToCurrency = {
  // --- North America ---
  'United States': { currency: 'USD', locale: 'en-US' },
  'Canada': { currency: 'CAD', locale: 'en-CA' },
  'Mexico': { currency: 'MXN', locale: 'es-MX' },

  // --- South America / Latin America ---
  'Argentina': { currency: 'ARS', locale: 'es-AR' },
  'Brazil': { currency: 'BRL', locale: 'pt-BR' },
  'Chile': { currency: 'CLP', locale: 'es-CL' },
  'Colombia': { currency: 'COP', locale: 'es-CO' },
  'Peru': { currency: 'PEN', locale: 'es-PE' },
  'Uruguay': { currency: 'UYU', locale: 'es-UY' },
  'Paraguay': { currency: 'PYG', locale: 'es-PY' },
  'Venezuela': { currency: 'VES', locale: 'es-VE' },
  'Ecuador': { currency: 'USD', locale: 'es-EC' },
  'Bolivia': { currency: 'BOB', locale: 'es-BO' },
  'Costa Rica': { currency: 'CRC', locale: 'es-CR' },
  'Panama': { currency: 'PAB', locale: 'es-PA' },
  'Guatemala': { currency: 'GTQ', locale: 'es-GT' },
  'El Salvador': { currency: 'USD', locale: 'es-SV' },
  'Honduras': { currency: 'HNL', locale: 'es-HN' },
  'Nicaragua': { currency: 'NIO', locale: 'es-NI' },
  'Dominican Republic': { currency: 'DOP', locale: 'es-DO' },
  'Cuba': { currency: 'CUP', locale: 'es-CU' },
  'Jamaica': { currency: 'JMD', locale: 'en-JM' },
  'Trinidad and Tobago': { currency: 'TTD', locale: 'en-TT' },

  // --- Europe ---
  'United Kingdom': { currency: 'GBP', locale: 'en-GB' },
  'France': { currency: 'EUR', locale: 'fr-FR' },
  'Germany': { currency: 'EUR', locale: 'de-DE' },
  'Italy': { currency: 'EUR', locale: 'it-IT' },
  'Spain': { currency: 'EUR', locale: 'es-ES' },
  'Portugal': { currency: 'EUR', locale: 'pt-PT' },
  'Netherlands': { currency: 'EUR', locale: 'nl-NL' },
  'Belgium': { currency: 'EUR', locale: 'fr-BE' },
  'Switzerland': { currency: 'CHF', locale: 'de-CH' },
  'Austria': { currency: 'EUR', locale: 'de-AT' },
  'Sweden': { currency: 'SEK', locale: 'sv-SE' },
  'Norway': { currency: 'NOK', locale: 'nb-NO' },
  'Denmark': { currency: 'DKK', locale: 'da-DK' },
  'Finland': { currency: 'EUR', locale: 'fi-FI' },
  'Ireland': { currency: 'EUR', locale: 'en-IE' },
  'Poland': { currency: 'PLN', locale: 'pl-PL' },
  'Czech Republic': { currency: 'CZK', locale: 'cs-CZ' },
  'Hungary': { currency: 'HUF', locale: 'hu-HU' },
  'Slovakia': { currency: 'EUR', locale: 'sk-SK' },
  'Slovenia': { currency: 'EUR', locale: 'sl-SI' },
  'Croatia': { currency: 'EUR', locale: 'hr-HR' },
  'Greece': { currency: 'EUR', locale: 'el-GR' },
  'Romania': { currency: 'RON', locale: 'ro-RO' },
  'Bulgaria': { currency: 'BGN', locale: 'bg-BG' },
  'Serbia': { currency: 'RSD', locale: 'sr-RS' },
  'Bosnia and Herzegovina': { currency: 'BAM', locale: 'bs-BA' },
  'North Macedonia': { currency: 'MKD', locale: 'mk-MK' },
  'Albania': { currency: 'ALL', locale: 'sq-AL' },
  'Iceland': { currency: 'ISK', locale: 'is-IS' },
  'Ukraine': { currency: 'UAH', locale: 'uk-UA' },
  'Belarus': { currency: 'BYN', locale: 'be-BY' },
  'Russia': { currency: 'RUB', locale: 'ru-RU' },
  'Georgia': { currency: 'GEL', locale: 'ka-GE' },
  'Armenia': { currency: 'AMD', locale: 'hy-AM' },
  'Azerbaijan': { currency: 'AZN', locale: 'az-AZ' },

  // --- Middle East ---
  'United Arab Emirates': { currency: 'AED', locale: 'ar-AE' },
  'Saudi Arabia': { currency: 'SAR', locale: 'ar-SA' },
  'Bahrain': { currency: 'BHD', locale: 'ar-BH' },
  'Qatar': { currency: 'QAR', locale: 'ar-QA' },
  'Kuwait': { currency: 'KWD', locale: 'ar-KW' },
  'Oman': { currency: 'OMR', locale: 'ar-OM' },
  'Jordan': { currency: 'JOD', locale: 'ar-JO' },
  'Lebanon': { currency: 'LBP', locale: 'ar-LB' },
  'Syria': { currency: 'SYP', locale: 'ar-SY' },
  'Iraq': { currency: 'IQD', locale: 'ar-IQ' },
  'Yemen': { currency: 'YER', locale: 'ar-YE' },
  'Iran': { currency: 'IRR', locale: 'fa-IR' },
  'Israel': { currency: 'ILS', locale: 'he-IL' },
  'Palestine': { currency: 'ILS', locale: 'ar-PS' },

  // --- North Africa (MENA) ---
  'Egypt': { currency: 'EGP', locale: 'ar-EG' },
  'Libya': { currency: 'LYD', locale: 'ar-LY' },
  'Tunisia': { currency: 'TND', locale: 'ar-TN' },
  'Algeria': { currency: 'DZD', locale: 'ar-DZ' },
  'Morocco': { currency: 'MAD', locale: 'ar-MA' },
  'Sudan': { currency: 'SDG', locale: 'ar-SD' },
  'Mauritania': { currency: 'MRU', locale: 'ar-MR' },
  'Somalia': { currency: 'SOS', locale: 'so-SO' },
  'Djibouti': { currency: 'DJF', locale: 'fr-DJ' },

  // --- Central Asia ---
  'Afghanistan': { currency: 'AFN', locale: 'fa-AF' },
  'Kazakhstan': { currency: 'KZT', locale: 'kk-KZ' },
  'Uzbekistan': { currency: 'UZS', locale: 'uz-UZ' },
  'Turkmenistan': { currency: 'TMT', locale: 'tk-TM' },
  'Kyrgyzstan': { currency: 'KGS', locale: 'ky-KG' },
  'Tajikistan': { currency: 'TJS', locale: 'tg-TJ' },

  // --- South Asia ---
  'India': { currency: 'INR', locale: 'en-IN' },
  'Pakistan': { currency: 'PKR', locale: 'ur-PK' },
  'Bangladesh': { currency: 'BDT', locale: 'bn-BD' },
  'Sri Lanka': { currency: 'LKR', locale: 'si-LK' },
  'Nepal': { currency: 'NPR', locale: 'ne-NP' },
  'Bhutan': { currency: 'BTN', locale: 'dz-BT' },
  'Maldives': { currency: 'MVR', locale: 'dv-MV' },

  // --- East Asia ---
  'China': { currency: 'CNY', locale: 'zh-CN' },
  'Japan': { currency: 'JPY', locale: 'ja-JP' },
  'South Korea': { currency: 'KRW', locale: 'ko-KR' },
  'North Korea': { currency: 'KPW', locale: 'ko-KP' },
  'Mongolia': { currency: 'MNT', locale: 'mn-MN' },
  'Taiwan': { currency: 'TWD', locale: 'zh-TW' },
  'Hong Kong': { currency: 'HKD', locale: 'zh-HK' },
  'Macau': { currency: 'MOP', locale: 'zh-MO' },

  // --- Southeast Asia ---
  'Indonesia': { currency: 'IDR', locale: 'id-ID' },
  'Malaysia': { currency: 'MYR', locale: 'ms-MY' },
  'Thailand': { currency: 'THB', locale: 'th-TH' },
  'Vietnam': { currency: 'VND', locale: 'vi-VN' },
  'Philippines': { currency: 'PHP', locale: 'en-PH' },
  'Singapore': { currency: 'SGD', locale: 'en-SG' },
  'Myanmar': { currency: 'MMK', locale: 'my-MM' },
  'Cambodia': { currency: 'KHR', locale: 'km-KH' },
  'Laos': { currency: 'LAK', locale: 'lo-LA' },
  'Brunei': { currency: 'BND', locale: 'ms-BN' },
  'Timor-Leste': { currency: 'USD', locale: 'pt-TL' },

  // --- Oceania ---
  'Australia': { currency: 'AUD', locale: 'en-AU' },
  'New Zealand': { currency: 'NZD', locale: 'en-NZ' },
  'Fiji': { currency: 'FJD', locale: 'en-FJ' },
  'Papua New Guinea': { currency: 'PGK', locale: 'en-PG' },
  'Samoa': { currency: 'WST', locale: 'en-WS' },
  'Tonga': { currency: 'TOP', locale: 'en-TO' },
  'Vanuatu': { currency: 'VUV', locale: 'en-VU' },

  // --- Africa ---
  'South Africa': { currency: 'ZAR', locale: 'en-ZA' },
  'Nigeria': { currency: 'NGN', locale: 'en-NG' },
  'Kenya': { currency: 'KES', locale: 'en-KE' },
  'Ghana': { currency: 'GHS', locale: 'en-GH' },
  'Ethiopia': { currency: 'ETB', locale: 'am-ET' },
  'Tanzania': { currency: 'TZS', locale: 'sw-TZ' },
  'Uganda': { currency: 'UGX', locale: 'en-UG' },
  'Rwanda': { currency: 'RWF', locale: 'en-RW' },
  'Burundi': { currency: 'BIF', locale: 'fr-BI' },
  'Zimbabwe': { currency: 'ZWL', locale: 'en-ZW' },
  'Zambia': { currency: 'ZMW', locale: 'en-ZM' },
  'Malawi': { currency: 'MWK', locale: 'en-MW' },
  'Botswana': { currency: 'BWP', locale: 'en-BW' },
  'Namibia': { currency: 'NAD', locale: 'en-NA' },
  'Angola': { currency: 'AOA', locale: 'pt-AO' },
  'Cameroon': { currency: 'XAF', locale: 'fr-CM' },
  'Congo': { currency: 'CDF', locale: 'fr-CG' },
  'Democratic Republic of the Congo': { currency: 'CDF', locale: 'fr-CD' },
  'Senegal': { currency: 'XOF', locale: 'fr-SN' },
  'Ivory Coast': { currency: 'XOF', locale: 'fr-CI' },
  'Mali': { currency: 'XOF', locale: 'fr-ML' },
  'Niger': { currency: 'XOF', locale: 'fr-NE' },
  'Togo': { currency: 'XOF', locale: 'fr-TG' },
  'Benin': { currency: 'XOF', locale: 'fr-BJ' },
  'Burkina Faso': { currency: 'XOF', locale: 'fr-BF' },
  'Guinea': { currency: 'GNF', locale: 'fr-GN' },
  'Sierra Leone': { currency: 'SLL', locale: 'en-SL' },
  'Liberia': { currency: 'LRD', locale: 'en-LR' },
  'Chad': { currency: 'XAF', locale: 'fr-TD' },
  'Gabon': { currency: 'XAF', locale: 'fr-GA' },
  'Equatorial Guinea': { currency: 'XAF', locale: 'fr-GQ' },
  'Central African Republic': { currency: 'XAF', locale: 'fr-CF' },
  'Madagascar': { currency: 'MGA', locale: 'fr-MG' },
  'Mauritius': { currency: 'MUR', locale: 'en-MU' },
  'Seychelles': { currency: 'SCR', locale: 'en-SC' },
  'Eritrea': { currency: 'ERN', locale: 'ti-ER' }
};