export const languages = [
  "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Assamese", "Aymara", "Azerbaijani",
  "Bambara", "Basque", "Belarusian", "Bengali", "Bhojpuri", "Bosnian", "Bulgarian", "Burmese",
  "Catalan", "Cebuano", "Chichewa", "Chinese (Simplified)", "Chinese (Traditional)", "Corsican",
  "Croatian", "Czech", "Danish", "Dhivehi", "Dogri", "Dutch", "English", "Esperanto", "Estonian",
  "Ewe", "Filipino", "Finnish", "French", "Frisian", "Galician", "Georgian", "German", "Greek",
  "Guarani", "Gujarati", "Haitian Creole", "Hausa", "Hawaiian", "Hebrew", "Hindi", "Hmong",
  "Hungarian", "Icelandic", "Igbo", "Ilocano", "Indonesian", "Irish", "Italian", "Japanese",
  "Javanese", "Kannada", "Kazakh", "Khmer", "Kinyarwanda", "Konkani", "Korean", "Krio",
  "Kurdish (Kurmanji)", "Kurdish (Sorani)", "Kyrgyz", "Lao", "Latin", "Latvian", "Lingala",
  "Lithuanian", "Luganda", "Luxembourgish", "Macedonian", "Maithili", "Malagasy", "Malay",
  "Malayalam", "Maltese", "Maori", "Marathi", "Meiteilon", "Mizo", "Mongolian", "Nepali",
  "Norwegian", "Odia", "Oromo", "Pashto", "Persian", "Polish", "Portuguese", "Punjabi",
  "Quechua", "Romanian", "Russian", "Samoan", "Sanskrit", "Scots Gaelic", "Sepedi", "Serbian",
  "Sesotho", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovenian", "Somali", "Spanish",
  "Sundanese", "Swahili", "Swedish", "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Tigrinya",
  "Tsonga", "Turkish", "Turkmen", "Twi", "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese",
  "Welsh", "Xhosa", "Yiddish", "Yoruba", "Zulu"
];

// Country → multiple recommended languages
export const countryToLanguage = {
  France: ["French"],
  Japan: ["Japanese"],
  Germany: ["German"],
  Spain: ["Spanish"],
  Italy: ["Italian"],
  Portugal: ["Portuguese"],
  Russia: ["Russian"],
  China: ["Chinese (Simplified)", "Chinese (Traditional)"],
  India: ["English", "Hindi", "Bengali", "Tamil", "Telugu", "Marathi"],
  Brazil: ["Portuguese"],
  Mexico: ["Spanish"],
  Argentina: ["Spanish"],
  Colombia: ["Spanish"],
  Peru: ["Spanish"],
  Venezuela: ["Spanish"],
  Chile: ["Spanish"],
  Ecuador: ["Spanish"],
  Guatemala: ["Spanish"],
  Cuba: ["Spanish"],
  "Dominican Republic": ["Spanish"],
  Honduras: ["Spanish"],
  Paraguay: ["Spanish"],
  "El Salvador": ["Spanish"],
  Nicaragua: ["Spanish"],
  "Costa Rica": ["Spanish"],
  Panama: ["Spanish"],
  Uruguay: ["Spanish"],
  Bolivia: ["Spanish", "Quechua", "Aymara"],
  Netherlands: ["Dutch"],
  Belgium: ["Dutch", "French", "German"],
  Sweden: ["Swedish"],
  Finland: ["Finnish", "Swedish"],
  Norway: ["Norwegian"],
  Denmark: ["Danish"],
  Iceland: ["Icelandic"],
  Poland: ["Polish"],
  Ukraine: ["Ukrainian"],
  Romania: ["Romanian"],
  Hungary: ["Hungarian"],
  "Czech Republic": ["Czech"],
  Slovakia: ["Slovak"],
  Austria: ["German"],
  Switzerland: ["German", "French", "Italian", "Romansh"],
  Greece: ["Greek"],
  Turkey: ["Turkish"],
  Israel: ["Hebrew", "Arabic"],
  "Saudi Arabia": ["Arabic"],
  Egypt: ["Arabic"],
  Iran: ["Persian"],
  Iraq: ["Arabic", "Kurdish (Sorani)"],
  Afghanistan: ["Pashto", "Dari"],
  Pakistan: ["Urdu", "Punjabi", "Sindhi"],
  Bangladesh: ["Bengali"],
  Thailand: ["Thai"],
  Vietnam: ["Vietnamese"],
  Indonesia: ["Indonesian"],
  Malaysia: ["Malay", "English"],
  Philippines: ["Filipino", "English"],
  "South Korea": ["Korean"],
  "North Korea": ["Korean"],
  "South Africa": ["English", "Zulu", "Afrikaans", "Xhosa"],
  Nigeria: ["English", "Hausa", "Yoruba", "Igbo"],
  Kenya: ["English", "Swahili"],
  Ethiopia: ["Amharic"],
  Morocco: ["Arabic"],
  Algeria: ["Arabic"],
  Tunisia: ["Arabic"],
  Canada: ["English", "French"],
  Australia: ["English"],
  "New Zealand": ["English", "Maori"],
  "United Kingdom": ["English"],
  Ireland: ["English", "Irish"],
  "United States": ["English", "Spanish"],
  Bahrain: ["Arabic"],
  Cyprus: ["Greek", "Turkish"],
  Jordan: ["Arabic"],
  Kuwait: ["Arabic", "English"],
  Lebanon: ["Arabic", "French", "English"],
  Oman: ["Arabic"],
  Qatar: ["Arabic"],
  "United Arab Emirates": ["Arabic", "English"],
  Yemen: ["Arabic"],
};

export const countryCodeToName = {
  "AF": "Afghanistan", "AX": "Åland Islands", "AL": "Albania", "DZ": "Algeria",
  "AS": "American Samoa", "AD": "Andorra", "AO": "Angola", "AI": "Anguilla",
  "AQ": "Antarctica", "AG": "Antigua and Barbuda", "AR": "Argentina", "AM": "Armenia",
  "AW": "Aruba", "AU": "Australia", "AT": "Austria", "AZ": "Azerbaijan",
  "BS": "Bahamas", "BH": "Bahrain", "BD": "Bangladesh", "BB": "Barbados",
  "BY": "Belarus", "BE": "Belgium", "BZ": "Belize", "BJ": "Benin",
  "BM": "Bermuda", "BT": "Bhutan", "BO": "Bolivia", "BQ": "Bonaire",
  "BA": "Bosnia and Herzegovina", "BW": "Botswana", "BV": "Bouvet Island",
  "BR": "Brazil", "IO": "British Indian Ocean Territory", "BN": "Brunei Darussalam",
  "BG": "Bulgaria", "BF": "Burkina Faso", "BI": "Burundi", "CV": "Cabo Verde",
  "KH": "Cambodia", "CM": "Cameroon", "CA": "Canada", "KY": "Cayman Islands",
  "CF": "Central African Republic", "TD": "Chad", "CL": "Chile", "CN": "China",
  "CX": "Christmas Island", "CC": "Cocos Islands", "CO": "Colombia", "KM": "Comoros",
  "CG": "Congo", "CD": "Congo", "CK": "Cook Islands", "CR": "Costa Rica",
  "CI": "Côte d'Ivoire", "HR": "Croatia", "CU": "Cuba", "CW": "Curaçao",
  "CY": "Cyprus", "CZ": "Czechia", "DK": "Denmark", "DJ": "Djibouti",
  "DM": "Dominica", "DO": "Dominican Republic", "EC": "Ecuador", "EG": "Egypt",
  "SV": "El Salvador", "GQ": "Equatorial Guinea", "ER": "Eritrea", "EE": "Estonia",
  "SZ": "Eswatini", "ET": "Ethiopia", "FK": "Falkland Islands", "FO": "Faroe Islands",
  "FJ": "Fiji", "FI": "Finland", "FR": "France", "GF": "French Guiana",
  "PF": "French Polynesia", "TF": "French Southern Territories", "GA": "Gabon",
  "GM": "Gambia", "GE": "Georgia", "DE": "Germany", "GH": "Ghana",
  "GI": "Gibraltar", "GR": "Greece", "GL": "Greenland", "GD": "Grenada",
  "GP": "Guadeloupe", "GU": "Guam", "GT": "Guatemala", "GG": "Guernsey",
  "GN": "Guinea", "GW": "Guinea-Bissau", "GY": "Guyana", "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands", "VA": "Holy See", "HN": "Honduras",
  "HK": "Hong Kong", "HU": "Hungary", "IS": "Iceland", "IN": "India",
  "ID": "Indonesia", "IR": "Iran", "IQ": "Iraq", "IE": "Ireland",
  "IM": "Isle of Man", "IL": "Israel", "IT": "Italy", "JM": "Jamaica",
  "JP": "Japan", "JE": "Jersey", "JO": "Jordan", "KZ": "Kazakhstan",
  "KE": "Kenya", "KI": "Kiribati", "KP": "North Korea", "KR": "South Korea",
  "KW": "Kuwait", "KG": "Kyrgyzstan", "LA": "Lao", "LV": "Latvia",
  "LB": "Lebanon", "LS": "Lesotho", "LR": "Liberia", "LY": "Libya",
  "LI": "Liechtenstein", "LT": "Lithuania", "LU": "Luxembourg", "MO": "Macao",
  "MG": "Madagascar", "MW": "Malawi", "MY": "Malaysia", "MV": "Maldives",
  "ML": "Mali", "MT": "Malta", "MH": "Marshall Islands", "MQ": "Martinique",
  "MR": "Mauritania", "MU": "Mauritius", "YT": "Mayotte", "MX": "Mexico",
  "FM": "Micronesia", "MD": "Moldova", "MC": "Monaco", "MN": "Mongolia",
  "ME": "Montenegro", "MS": "Montserrat", "MA": "Morocco", "MZ": "Mozambique",
  "MM": "Myanmar", "NA": "Namibia", "NR": "Nauru", "NP": "Nepal",
  "NL": "Netherlands", "NC": "New Caledonia", "NZ": "New Zealand", "NI": "Nicaragua",
  "NE": "Niger", "NG": "Nigeria", "NU": "Niue", "NF": "Norfolk Island",
  "MK": "North Macedonia", "MP": "Northern Mariana Islands", "NO": "Norway",
  "OM": "Oman", "PK": "Pakistan", "PW": "Palau", "PS": "Palestine",
  "PA": "Panama", "PG": "Papua New Guinea", "PY": "Paraguay", "PE": "Peru",
  "PH": "Philippines", "PN": "Pitcairn", "PL": "Poland", "PT": "Portugal",
  "PR": "Puerto Rico", "QA": "Qatar", "RE": "Réunion", "RO": "Romania",
  "RU": "Russia", "RW": "Rwanda", "BL": "Saint Barthélemy", "SH": "Saint Helena",
  "KN": "Saint Kitts and Nevis", "LC": "Saint Lucia", "MF": "Saint Martin",
  "PM": "Saint Pierre and Miquelon", "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa", "SM": "San Marino", "ST": "Sao Tome and Principe", "SA": "Saudi Arabia",
  "SN": "Senegal", "RS": "Serbia", "SC": "Seychelles", "SL": "Sierra Leone",
  "SG": "Singapore", "SX": "Sint Maarten", "SK": "Slovakia", "SI": "Slovenia",
  "SB": "Solomon Islands", "SO": "Somalia", "ZA": "South Africa", "GS": "South Georgia",
  "SS": "South Sudan", "ES": "Spain", "LK": "Sri Lanka", "SD": "Sudan",
  "SR": "Suriname", "SJ": "Svalbard and Jan Mayen", "SE": "Sweden", "CH": "Switzerland",
  "SY": "Syrian Arab Republic", "TW": "Taiwan", "TJ": "Tajikistan", "TZ": "Tanzania",
  "TH": "Thailand", "TL": "Timor-Leste", "TG": "Togo", "TK": "Tokelau",
  "TO": "Tonga", "TT": "Trinidad and Tobago", "TN": "Tunisia", "TR": "Turkey",
  "TM": "Turkmenistan", "TC": "Turks and Caicos Islands", "TV": "Tuvalu",
  "UG": "Uganda", "UA": "Ukraine", "AE": "United Arab Emirates", "GB": "United Kingdom",
  "US": "United States", "UM": "United States Minor Outlying Islands", "UY": "Uruguay",
  "UZ": "Uzbekistan", "VU": "Vanuatu", "VE": "Venezuela", "VN": "Vietnam",
  "VG": "Virgin Islands (British)", "VI": "Virgin Islands (U.S.)", "WF": "Wallis and Futuna",
  "EH": "Western Sahara", "YE": "Yemen", "ZM": "Zambia", "ZW": "Zimbabwe"
};