export const languages = [
  "Global English",
  "Australian English",
  "British English",
  "US English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Hindi",
  "Japanese",
  "Chinese",
  "Finnish",
  "Korean",
  "Polish",
  "Russian",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Croatian",
  "Czech",
  "Danish",
  "Estonian",
  "Faroese",
  "Galician",
  "Georgian",
  "Greek",
  "Gujarati",
  "Haitian",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Norwegian Nynorsk",
  "Occitan",
  "Panjabi",
  "Pashto",
  "Persian",
  "Romanian",
  "Sanskrit",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Turkmen",
  "Urdu",
  "Uzbek",
  "Welsh",
  "Yiddish",
  "Yoruba"
];

export const multilingualStreaming = ["English", "Spanish", "French", "German", "Italian", "Portuguese"];

export const languageRegions = {
  europe: [
    "Global English", "British English", "French", "German", "Italian", "Portuguese",
    "Spanish", "Dutch", "Finnish", "Polish", "Russian", "Ukrainian", "Albanian",
    "Basque", "Belarusian", "Bosnian", "Breton", "Bulgarian", "Catalan", "Croatian",
    "Czech", "Danish", "Estonian", "Faroese", "Galician", "Georgian", "Greek",
    "Hungarian", "Icelandic", "Irish", "Latvian", "Lithuanian", "Luxembourgish",
    "Macedonian", "Maltese", "Norwegian", "Norwegian Nynorsk", "Occitan", "Romanian",
    "Serbian", "Slovak", "Slovenian", "Swedish", "Welsh", "Yiddish"
  ],
  asia: [
    "Hindi", "Japanese", "Chinese", "Korean", "Vietnamese", "Armenian", "Assamese",
    "Azerbaijani", "Bengali", "Burmese", "Gujarati", "Indonesian", "Javanese",
    "Kannada", "Kazakh", "Khmer", "Lao", "Malay", "Malayalam", "Marathi", "Mongolian",
    "Nepali", "Panjabi", "Pashto", "Persian", "Sanskrit", "Sindhi", "Sinhala",
    "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Tibetan", "Turkmen", "Urdu",
    "Uzbek"
  ],
  americas: [
    "US English", "Spanish", "Portuguese", "French", "Dutch", "Haitian", "Quechua"
  ],
  africa: [
    "Afrikaans", "Amharic", "Arabic", "Hausa", "Lingala", "Malagasy", "Shona",
    "Somali", "Swahili", "Yoruba"
  ],
  middleEast: [
    "Arabic", "Hebrew", "Persian", "Turkish", "Kurdish"
  ],
  pacific: [
    "Australian English", "Maori", "Hawaiian", "Tagalog", "Sundanese"
  ]
};

// Country → multiple recommended languages (updated with new language list)
export const countryToLanguage = {
  // English-speaking countries
  "United States": ["US English", "Spanish"],
  "United Kingdom": ["British English"],
  Australia: ["Australian English"],
  Canada: ["Global English", "French"],
  "New Zealand": ["Global English", "Maori"],
  Ireland: ["Global English"],
  India: ["Hindi", "English", "Bengali", "Tamil", "Telugu", "Marathi"],
  Philippines: ["Tagalog", "English"],
  Malaysia: ["Malay", "English"],
  Singapore: ["English", "Chinese", "Malay", "Tamil"],
  "South Africa": ["English", "Afrikaans", "Zulu", "Xhosa"],

  // European countries
  France: ["French"],
  Germany: ["German"],
  Spain: ["Spanish", "Catalan", "Galician", "Basque"],
  Italy: ["Italian"],
  Portugal: ["Portuguese"],
  Netherlands: ["Dutch"],
  Belgium: ["Dutch", "French", "German"],
  Switzerland: ["German", "French", "Italian"],
  Austria: ["German"],
  Sweden: ["Swedish"],
  Norway: ["Norwegian"],
  Denmark: ["Danish"],
  Finland: ["Finnish", "Swedish"],
  Poland: ["Polish"],
  "Czech Republic": ["Czech"],
  Slovakia: ["Slovak"],
  Hungary: ["Hungarian"],
  Romania: ["Romanian"],
  Bulgaria: ["Bulgarian"],
  Greece: ["Greek"],
  Russia: ["Russian"],
  Ukraine: ["Ukrainian"],
  Belarus: ["Belarusian"],
  Croatia: ["Croatian"],
  Serbia: ["Serbian"],
  Slovenia: ["Slovenian"],
  Bosnia: ["Bosnian"],
  Albania: ["Albanian"],
  Lithuania: ["Lithuanian"],
  Latvia: ["Latvian"],
  Estonia: ["Estonian"],
  Iceland: ["Icelandic"],
  Luxembourg: ["Luxembourgish", "French", "German"],

  // Asian countries
  China: ["Chinese"],
  Japan: ["Japanese"],
  "South Korea": ["Korean"],
  Vietnam: ["Vietnamese"],
  Thailand: ["Thai"],
  Indonesia: ["Indonesian", "Javanese"],
  Turkey: ["Turkish"],
  Israel: ["Hebrew", "Arabic"],
  "Saudi Arabia": ["Arabic"],
  Iran: ["Persian"],
  Afghanistan: ["Pashto", "Persian"],
  Pakistan: ["Urdu", "Panjabi"],
  Bangladesh: ["Bengali"],
  Kazakhstan: ["Kazakh", "Russian"],
  Uzbekistan: ["Uzbek"],
  Tajikistan: ["Tajik"],
  Turkmenistan: ["Turkmen"],
  Kyrgyzstan: ["Kyrgyz"],
  Mongolia: ["Mongolian"],
  Myanmar: ["Burmese"],
  Laos: ["Lao"],
  Cambodia: ["Khmer"],
  Nepal: ["Nepali"],
  "Sri Lanka": ["Sinhala", "Tamil"],

  // Middle Eastern countries
  Egypt: ["Arabic"],
  Iraq: ["Arabic", "Kurdish"],
  "United Arab Emirates": ["Arabic"],
  Qatar: ["Arabic"],
  Kuwait: ["Arabic"],
  Oman: ["Arabic"],
  Bahrain: ["Arabic"],
  Jordan: ["Arabic"],
  Lebanon: ["Arabic"],
  Syria: ["Arabic"],
  Yemen: ["Arabic"],

  // African countries
  Nigeria: ["English", "Hausa", "Yoruba"],
  Ethiopia: ["Amharic"],
  Kenya: ["Swahili", "English"],
  Tanzania: ["Swahili"],
  Uganda: ["Swahili", "English"],
  Ghana: ["English"],
  "Congo (DRC)": ["French", "Lingala"],
  "Congo (Republic)": ["French"],
  Cameroon: ["French", "English"],
  "Ivory Coast": ["French"],
  Senegal: ["French"],
  Mali: ["French"],
  Burkina: ["French"],
  Niger: ["French"],
  Chad: ["French", "Arabic"],
  Sudan: ["Arabic"],
  "South Sudan": ["Arabic", "English"],
  Madagascar: ["Malagasy", "French"],
  Mozambique: ["Portuguese"],
  Angola: ["Portuguese"],
  Zambia: ["English"],
  Zimbabwe: ["English", "Shona"],
  Namibia: ["English", "Afrikaans"],
  Botswana: ["English"],
  Mauritius: ["English", "French"],
  Seychelles: ["English", "French"],

  // Latin American countries
  Brazil: ["Portuguese"],
  Mexico: ["Spanish"],
  Argentina: ["Spanish"],
  Colombia: ["Spanish"],
  Peru: ["Spanish", "Quechua"],
  Chile: ["Spanish"],
  Venezuela: ["Spanish"],
  Ecuador: ["Spanish"],
  Guatemala: ["Spanish"],
  Cuba: ["Spanish"],
  "Dominican Republic": ["Spanish"],
  Honduras: ["Spanish"],
  Paraguay: ["Spanish", "Guarani"],
  "El Salvador": ["Spanish"],
  Nicaragua: ["Spanish"],
  "Costa Rica": ["Spanish"],
  Panama: ["Spanish"],
  Uruguay: ["Spanish"],
  Bolivia: ["Spanish", "Quechua", "Aymara"],
  Haiti: ["Haitian", "French"],

  // Other regions
  "Papua New Guinea": ["English", "Tok Pisin"],
  Fiji: ["English", "Fijian"],
  "Solomon Islands": ["English"],
  Vanuatu: ["English", "French", "Bislama"]
};

export const countryCodeToName = {
  "AF": "Afghanistan", "AL": "Albania", "DZ": "Algeria", "AD": "Andorra", "AO": "Angola",
  "AG": "Antigua and Barbuda", "AR": "Argentina", "AM": "Armenia", "AU": "Australia",
  "AT": "Austria", "AZ": "Azerbaijan", "BS": "Bahamas", "BH": "Bahrain", "BD": "Bangladesh",
  "BB": "Barbados", "BY": "Belarus", "BE": "Belgium", "BZ": "Belize", "BJ": "Benin",
  "BT": "Bhutan", "BO": "Bolivia", "BA": "Bosnia and Herzegovina", "BW": "Botswana",
  "BR": "Brazil", "BN": "Brunei Darussalam", "BG": "Bulgaria", "BF": "Burkina Faso",
  "BI": "Burundi", "CV": "Cabo Verde", "KH": "Cambodia", "CM": "Cameroon", "CA": "Canada",
  "CF": "Central African Republic", "TD": "Chad", "CL": "Chile", "CN": "China",
  "CO": "Colombia", "KM": "Comoros", "CG": "Congo", "CD": "Congo", "CR": "Costa Rica",
  "CI": "Côte d'Ivoire", "HR": "Croatia", "CU": "Cuba", "CY": "Cyprus", "CZ": "Czechia",
  "DK": "Denmark", "DJ": "Djibouti", "DM": "Dominica", "DO": "Dominican Republic",
  "EC": "Ecuador", "EG": "Egypt", "SV": "El Salvador", "GQ": "Equatorial Guinea",
  "ER": "Eritrea", "EE": "Estonia", "SZ": "Eswatini", "ET": "Ethiopia", "FJ": "Fiji",
  "FI": "Finland", "FR": "France", "GA": "Gabon", "GM": "Gambia", "GE": "Georgia",
  "DE": "Germany", "GH": "Ghana", "GR": "Greece", "GD": "Grenada", "GT": "Guatemala",
  "GN": "Guinea", "GW": "Guinea-Bissau", "GY": "Guyana", "HT": "Haiti", "HN": "Honduras",
  "HU": "Hungary", "IS": "Iceland", "IN": "India", "ID": "Indonesia", "IR": "Iran",
  "IQ": "Iraq", "IE": "Ireland", "IL": "Israel", "IT": "Italy", "JM": "Jamaica",
  "JP": "Japan", "JO": "Jordan", "KZ": "Kazakhstan", "KE": "Kenya", "KI": "Kiribati",
  "KP": "North Korea", "KR": "South Korea", "KW": "Kuwait", "KG": "Kyrgyzstan",
  "LA": "Lao", "LV": "Latvia", "LB": "Lebanon", "LS": "Lesotho", "LR": "Liberia",
  "LY": "Libya", "LI": "Liechtenstein", "LT": "Lithuanian", "LU": "Luxembourg",
  "MG": "Madagascar", "MW": "Malawi", "MY": "Malaysia", "MV": "Maldives", "ML": "Mali",
  "MT": "Malta", "MH": "Marshall Islands", "MR": "Mauritania", "MU": "Mauritius",
  "MX": "Mexico", "FM": "Micronesia", "MD": "Moldova", "MC": "Monaco", "MN": "Mongolia",
  "ME": "Montenegro", "MA": "Morocco", "MZ": "Mozambique", "MM": "Myanmar", "NA": "Namibia",
  "NR": "Nauru", "NP": "Nepal", "NL": "Netherlands", "NZ": "New Zealand", "NI": "Nicaragua",
  "NE": "Niger", "NG": "Nigeria", "MK": "North Macedonia", "NO": "Norway", "OM": "Oman",
  "PK": "Pakistan", "PW": "Palau", "PA": "Panama", "PG": "Papua New Guinea", "PY": "Paraguay",
  "PE": "Peru", "PH": "Philippines", "PL": "Poland", "PT": "Portugal", "QA": "Qatar",
  "RO": "Romania", "RU": "Russia", "RW": "Rwanda", "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia", "VC": "Saint Vincent and the Grenadines", "WS": "Samoa",
  "SM": "San Marino", "ST": "Sao Tome and Principe", "SA": "Saudi Arabia", "SN": "Senegal",
  "RS": "Serbia", "SC": "Seychelles", "SL": "Sierra Leone", "SG": "Singapore",
  "SK": "Slovakia", "SI": "Slovenia", "SB": "Solomon Islands", "SO": "Somalia",
  "ZA": "South Africa", "SS": "South Sudan", "ES": "Spain", "LK": "Sri Lanka", "SD": "Sudan",
  "SR": "Suriname", "SE": "Sweden", "CH": "Switzerland", "SY": "Syrian Arab Republic",
  "TW": "Taiwan", "TJ": "Tajikistan", "TZ": "Tanzania", "TH": "Thailand", "TL": "Timor-Leste",
  "TG": "Togo", "TO": "Tonga", "TT": "Trinidad and Tobago", "TN": "Tunisia", "TR": "Turkey",
  "TM": "Turkmenistan", "TV": "Tuvalu", "UG": "Uganda", "UA": "Ukraine",
  "AE": "United Arab Emirates", "GB": "United Kingdom", "US": "United States",
  "UY": "Uruguay", "UZ": "Uzbekistan", "VU": "Vanuatu", "VE": "Venezuela", "VN": "Vietnam",
  "YE": "Yemen", "ZM": "Zambia", "ZW": "Zimbabwe"
};