export const languages = [
  "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Assamese", "Aymara", "Azerbaijani",
  "Bambara", "Basque", "Belarusian", "Bengali", "Bhojpuri", "Bosnian", "Bulgarian", "Burmese",
  "Catalan", "Cebuano", "Chichewa", "Chinese (Simplified)", "Chinese (Traditional)", "Corsican",
  "Croatian", "Czech", "Danish", "Dhivehi", "Dogri", "Dutch", "English", "Esperanto", "Estonian",
  "Ewe", "Filipino", "Finnish", "French", "Frisian", "Galician", "Georgian", "German", "Greek",
  "Guarani", "Gujarati", "Haitian Creole", "Hausa", "Hawaiian", "Hebrew", "Hindi", "Hmong",
  "Hungarian", "Icelandic", "Igbo", "Ilocano", "Indonesian", "Irish", "Italian", "Japanese",
  "Javanese", "Kannada", "Kazakh", "Khmer", "Kinyarwanda", "Konkani", "Korean", "Krio",
  "Kurdish (Kurmanji)", "Kurdish (Sorani)", "Kyrgyz", "Lao", "Latin", "Latvian", "Lingala",
  "Lithuanian", "Luganda", "Luxembourgish", "Macedonian", "Maithili", "Malagasy", "Malay",
  "Malayalam", "Maltese", "Maori", "Marathi", "Meiteilon", "Mizo", "Mongolian", "Nepali",
  "Norwegian", "Odia", "Oromo", "Pashto", "Persian", "Polish", "Portuguese", "Punjabi",
  "Quechua", "Romanian", "Russian", "Samoan", "Sanskrit", "Scots Gaelic", "Sepedi", "Serbian",
  "Sesotho", "Shona", "Sindhi", "Sinhala", "Slovak", "Slovenian", "Somali", "Spanish",
  "Sundanese", "Swahili", "Swedish", "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Tigrinya",
  "Tsonga", "Turkish", "Turkmen", "Twi", "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese",
  "Welsh", "Xhosa", "Yiddish", "Yoruba", "Zulu"
];

// Country → multiple recommended languages
export const countryToLanguage = {
  France: ["French"],
  Japan: ["Japanese"],
  Germany: ["German"],
  Spain: ["Spanish"],
  Italy: ["Italian"],
  Portugal: ["Portuguese"],
  Russia: ["Russian"],
  China: ["Chinese (Simplified)", "Chinese (Traditional)"],
  India: ["English", "Hindi", "Bengali", "Tamil", "Telugu", "Marathi"],
  Brazil: ["Portuguese"],
  Mexico: ["Spanish"],
  Argentina: ["Spanish"],
  Colombia: ["Spanish"],
  Peru: ["Spanish"],
  Venezuela: ["Spanish"],
  Chile: ["Spanish"],
  Ecuador: ["Spanish"],
  Guatemala: ["Spanish"],
  Cuba: ["Spanish"],
  "Dominican Republic": ["Spanish"],
  Honduras: ["Spanish"],
  Paraguay: ["Spanish"],
  "El Salvador": ["Spanish"],
  Nicaragua: ["Spanish"],
  "Costa Rica": ["Spanish"],
  Panama: ["Spanish"],
  Uruguay: ["Spanish"],
  Bolivia: ["Spanish", "Quechua", "Aymara"],
  Netherlands: ["Dutch"],
  Belgium: ["Dutch", "French", "German"],
  Sweden: ["Swedish"],
  Finland: ["Finnish", "Swedish"],
  Norway: ["Norwegian"],
  Denmark: ["Danish"],
  Iceland: ["Icelandic"],
  Poland: ["Polish"],
  Ukraine: ["Ukrainian"],
  Romania: ["Romanian"],
  Hungary: ["Hungarian"],
  "Czech Republic": ["Czech"],
  Slovakia: ["Slovak"],
  Austria: ["German"],
  Switzerland: ["German", "French", "Italian", "Romansh"],
  Greece: ["Greek"],
  Turkey: ["Turkish"],
  Israel: ["Hebrew", "Arabic"],
  "Saudi Arabia": ["Arabic"],
  Egypt: ["Arabic"],
  Iran: ["Persian"],
  Iraq: ["Arabic", "Kurdish (Sorani)"],
  Afghanistan: ["Pashto", "Dari"],
  Pakistan: ["Urdu", "Punjabi", "Sindhi"],
  Bangladesh: ["Bengali"],
  Thailand: ["Thai"],
  Vietnam: ["Vietnamese"],
  Indonesia: ["Indonesian"],
  Malaysia: ["Malay", "English"],
  Philippines: ["Filipino", "English"],
  "South Korea": ["Korean"],
  "North Korea": ["Korean"],
  "South Africa": ["English", "Zulu", "Afrikaans", "Xhosa"],
  Nigeria: ["English", "Hausa", "Yoruba", "Igbo"],
  Kenya: ["English", "Swahili"],
  Ethiopia: ["Amharic"],
  Morocco: ["Arabic"],
  Algeria: ["Arabic"],
  Tunisia: ["Arabic"],
  Canada: ["English", "French"],
  Australia: ["English"],
  "New Zealand": ["English", "Maori"],
  "United Kingdom": ["English"],
  Ireland: ["English", "Irish"],
  "United States": ["English", "Spanish"],
  Bahrain: ["Arabic"],
  Cyprus: ["Greek", "Turkish"],
  Jordan: ["Arabic"],
  Kuwait: ["Arabic", "English"],
  Lebanon: ["Arabic", "French", "English"],
  Oman: ["Arabic"],
  Qatar: ["Arabic"],
  "United Arab Emirates": ["Arabic", "English"],
  Yemen: ["Arabic"],
};

